name: Build-Elite-Final
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos

      - name: Build Package
        run: |
          export THEOS=~/theos
          export PATH=$THEOS/bin:$PATH
          # Lệnh này sẽ tự dùng SDK mặc định của MacOS để build, không cần tải thêm
          make package FINALPACKAGE=1 TARGET=iphone:clang:latest:14.0
        env:
          THEOS: ~/theos

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Elite-Result
          path: packages/*.deb
